### ISSUE TITLE
DivisionByZeroError: Division by zero

### ISSUE THREAD

**Issue by lispstudent** [cosmocode/dokuwiki-plugin-photogallery#3]
While testing PhotoGallery Plugin with the example in the [docs](https://www.dokuwiki.org/plugin:photogallery#syntax):

```
---- photogallery show ----
namespace  : https://www.nasa.gov/rss/dyn/lg_image_of_the_day.rss
----
```

I get `DivisionByZeroError: Division by zero`

See this demo site I have been testing it:

https://www.gandharvalokapublishers.in/g1

**Comment by lispstudent** [comment]
Logs:

```
2023-01-11 18:01:03DivisionByZeroError: Division by zero /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/plugins/photogallery/syntax.php(668)
    #0 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/plugins/photogallery/syntax.php(528): syntax_plugin_photogallery->_image()
    #1 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/plugins/photogallery/syntax.php(586): syntax_plugin_photogallery->_lightgallery()
    #2 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/plugins/photogallery/syntax.php(314): syntax_plugin_photogallery->_poster()
    #3 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/plugins/photogallery/syntax.php(235): syntax_plugin_photogallery->_photo_gallery()
    #4 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/parser/renderer.php(117): syntax_plugin_photogallery->render()
    #5 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/parserutils.php(682): Doku_Renderer->plugin()
    #6 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/parserutils.php(149): p_render()
    #7 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/parserutils.php(89): p_cached_output()
    #8 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/Ui/PageView.php(68): p_wiki_xhtml()
    #9 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #10 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #11 [internal function]: tpl_content_core()
    #12 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/Extension/Event.php(133): call_user_func_array()
    #13 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
    #14 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
    #15 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content()
    #16 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/actions.php(27): include('...')
    #17 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/doku.php(126): act_dispatch()
    #18 {main} 
```

**Comment by annda** [comment]
Please re-install the plugin.

After adopting this plugin from the original developer, we are fixing issues as they arise. It might take a while before the DokuWiki extension manager registers a new version, so you might not see it as an available update.

**Comment by lispstudent** [comment]
Thank you for the update!

I have first updated the plugin with same results, then, completely uninstalled and then installed, with a similar log:

```
2023-01-12 06:24:44DivisionByZeroError: Division by zero /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/plugins/photogallery/syntax.php(671)
    #0 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/plugins/photogallery/syntax.php(528): syntax_plugin_photogallery->_image()
    #1 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/plugins/photogallery/syntax.php(586): syntax_plugin_photogallery->_lightgallery()
    #2 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/plugins/photogallery/syntax.php(314): syntax_plugin_photogallery->_poster()
    #3 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/plugins/photogallery/syntax.php(235): syntax_plugin_photogallery->_photo_gallery()
    #4 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/parser/renderer.php(117): syntax_plugin_photogallery->render()
    #5 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/parserutils.php(682): Doku_Renderer->plugin()
    #6 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/parserutils.php(149): p_render()
    #7 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/parserutils.php(89): p_cached_output()
    #8 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/Ui/PageView.php(68): p_wiki_xhtml()
    #9 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #10 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #11 [internal function]: tpl_content_core()
    #12 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/Extension/Event.php(133): call_user_func_array()
    #13 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
    #14 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
    #15 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content()
    #16 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/inc/actions.php(27): include('...')
    #17 /usr/local/www/apache24/data/gandharvalokapublishers.in/public_html/doku.php(126): act_dispatch()
    #18 {main} 
```
